<script lang="ts">
	import '../app.css';
	import { browser } from '$app/environment';
	import favicon from '$lib/assets/favicon.svg';
	import OfflineBanner from '$lib/components/OfflineBanner.svelte';

	let { children } = $props();

	if (browser) {
		// Registers the Workbox service worker generated by @vite-pwa/sveltekit
		// (see vite.config.ts) — not auto-injected since app.html isn't a
		// standard Vite entry HTML file.
		import('virtual:pwa-register/svelte').then(({ useRegisterSW }) => useRegisterSW());
	}
</script>

<svelte:head>
	<link rel="icon" href={favicon} />
</svelte:head>

<OfflineBanner />

{@render children()}
